sudo: false

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - libgtest-dev

before_script:
  - sudo sh .scripts/build-and-install-libgtest-libraries.sh
  - pip install --user cpp-coveralls

script:
  - make -j`nproc --all`
  - make check

after_success:
  - coveralls --exclude util/ --E '*-test.cpp' --gcov-options '\-lp'

notifications:
  email: false
